# Verifying yaml files: http://www.yamllint.com/ or https://github.com/adrienverge/yamllint
branches:
  only:
  - master

services:
  - docker

matrix:
  include:
    - mono: none
      os: linux
      dist: bionic # Ubuntu 18.04

install:
  - npm install -g tfx-cli
  - npm install -g typescript

script:
  - python3 --version
  - python3 script/updateversion.py
  - cd src
  - cd DockerTask
  - npm install
  - tsc
  - cd ..
  - cd DockerComposeTask
  - npm install
  - tsc
  - cd ..
  - tfx extension create

notifications:
  email: false