# Verifying yaml files: http://www.yamllint.com/ or https://github.com/adrienverge/yamllint

branches:
  only:
  - master

services:
  - docker

matrix:
  include:
    - mono: none
      os: linux
      dist: bionic # Ubuntu 18.04

stack: python "3.8"

install:
  - npm install -g tfx-cli

script:
  - python --version
  - python3 --version
  - python3 script/updateversion.py
  - cd src
  - npm install
  - tfx extension create

notifications:
  email: false