version: 1.0.{build}
os: Visual Studio 2019
skip_tags: true
configuration: Release

environment:
  devopsmarketplacePAT:
    secure: RSBRSDY8YUA95EpSdZjtbISWyWemugzG7lpwObh3S48mSOpZm0gAw1RB1f5s0KHbo4hnhZkTgYhYY1IHcsNGIg==

before_build:
  - SET PATH="C:\Python38";%path%
  - npm install -g tfx-cli
  - npm install -g typescript
  # - choco install 7zip

build_script:
  - python --version
  - python script/updateversion.py
  - cd src
  - cd buildAndReleaseTask
  - npm install
  - tsc
  - tfx extension create

after_test:
  - cmd: tfx extension publish --share-with avavedse avanadedigitalstudionl -t %devopsmarketplacePAT% --trace-level debug

artifacts:
- path: 'src/*.vsix'
  name: vsix

deploy:
- provider: GitHub
  auth_token:
    secure: do7S++r1rE5E3IZujCoMONsWYJNF7eoRoPyJbxSD851I850OlEq0gsHH/Tji7o00
  artifact: vsix
