version: 1.0.{build}
os: Visual Studio 2019
skip_tags: true
configuration: Release

# environment:

before_build:
  - npm install -g tfx-cli
  # - choco install 7zip

build_script:
  - python3 script/updateversion.py
  - cd src
  - npm install
  - tfx extension create

after_test:
  - cmd: echo Test test packing ...

artifacts:
- path: 'src/*.vsix'
  name: vsix

deploy:
- provider: GitHub
  auth_token:
    secure: do7S++r1rE5E3IZujCoMONsWYJNF7eoRoPyJbxSD851I850OlEq0gsHH/Tji7o00
  artifact: vsix
